version: "3"
services:
  app:
    container_name: dl-app
    build: .
    links:
      - db
    expose:
      - 5000
    depends_on:
      - db
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      SQLALCHEMY_DATABASE_URI: mysql://root:password@db:3306/deepcell-label
  visualizer:
    container_name: dl-visualizer
    build:
      context: visualizer
      dockerfile: Dockerfile
      args:
        - PUBLIC_URL=/
    expose:
      - 9000
    depends_on:
      app:
        condition: service_started
    environment:
      - NODE_ENV=production
      - PUBLIC_URL=/
  db:
    container_name: dl-db
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password
    expose:
      - 3306
    environment:
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: deepcell-label
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:rw
      - mysql:/var/lib/mysql/
  nginx:
    container_name: dl-nginx
    build: ./nginx
    restart: always
    ports:
      - "12345:80"
    depends_on:
      db:
        condition: service_started
      visualizer:
        condition: service_started
      app:
        condition: service_started
volumes:
  mysql:
    name: deepcell-label_mysql-data
